export type Overview = Record<string, number>;

export interface SessionInfo { telegram_id: number; username?: string | null; first_name?: string | null; version: string }
export interface TitleItem { id: string; slug: string; english_title: string; original_title: string; original_language: string; publication_status: string; description: string; boosty_url?: string | null; is_published: boolean; latest_chapter: number; published_at?: string | null; created_at: string }
export interface ReleaseItem { id: string; title_id: string; chapter_start: number; chapter_end: number; display_name?: string | null; chapter_label: string; boosty_url?: string | null; is_published: boolean; validation_status: string; validation_message?: string | null }
export interface UserItem { id: string; telegram_id: number; telegram_username?: string | null; anonymous_id: number; display_name?: string | null; is_active: boolean; manual_download_access: boolean; boosty_status: string; boosty_username?: string | null; grace_ends_at?: string | null; last_seen_at: string }
export interface SuggestionItem { id: string; original_title?: string | null; detected_language?: string | null; chapter_count?: number | null; requested_chapter_end?: number | null; publication_status?: string | null; status: string; vip_snapshot: boolean; duplicate_review_required: boolean; public_reason?: string | null; internal_note?: string | null; linked_title_id?: string | null; submitted_at?: string | null; raw_file?: { filename: string; size_bytes: number; validation_status: string } | null; user: { id: string; telegram_id: number; anonymous_id: number } }
export interface CommentItem { id: string; telegram_id: number; anonymous_id: number; target_type: string; original_body: string; public_body: string; replacement_count: number; vip_snapshot: boolean; is_deleted: boolean; created_at: string }
export interface RatingItem { id: string; release_id: string; release_label: string; score: number; feedback: string; status: string; vip_snapshot: boolean; telegram_id: number; anonymous_id: number; created_at: string }
export interface ReportItem { id: string; category: string; status: string; description: string; target_type: string; telegram_id: number; anonymous_id: number; created_at: string }
export interface BroadcastItem { id: string; status: string; audience_type: string; text: string; scheduled_at?: string | null; total_count: number; sent_count: number; failed_count: number; skipped_count: number; created_at: string }
export interface AuditItem { id: string; actor_telegram_id?: number | null; action: string; entity_type?: string | null; entity_id?: string | null; payload: Record<string, unknown>; created_at: string }
